### ISSUE TITLE
Update for slow parallax scroll

### ISSUE THREAD

**Issue by amyleesterling** [TEDxMusic/Wordpress-Theme#10]
"scrolling is really laggy once you enter the parallax image area on the start page. Not much, but noticeable. Might be even more of a problem if you try to keep that for mobile phones.
Problem appears to be that the resizing that large image is reeaally slow (or is it called every time you scroll?!). If you think this is an issue, what you could try to do, add:

background-size: initial;
background-color: black;
background-repeat: no-repeat;

to the #full-division-box

That will show the image in the original size (it is already centered in JavaScript) and scrolling becomes totally smooth again for me. If the users screen is wider than your image width (2684 pixel!), they'll see the image in the mid, and a black border at the left and the right. I think that should be ok."

from Nico Kemnitz

**Comment by zzimbler** [comment]
I'll take a look at this and hopefully we can make it a lot better

**Comment by amyleesterling** [comment]
ok thank you zach!

On Mon, Nov 24, 2014 at 1:01 PM, Zachary Zimbler notifications@github.com
wrote:

> I'll take a look at this and hopefully we can make it a lot better
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEDxMusic/Wordpress-Theme/issues/10#issuecomment-64235366
> .

## 

Creative Director, EyeWire http://eyewire.org/ | Founder, TEDx
Music Project https://soundcloud.com/tedxmusicproject
Twitter http://www.twitter.com/amyleerobinson

**Comment by amyleesterling** [comment]
Made these changes

**Comment by amyleesterling** [comment]
@zzimbler I made these changes but I can't tell if it will actually load on a slow connection - still relatively slow and the center image is zoomed in way too far.

**Comment by amyleesterling** [comment]
Also the central image is now way too zoomed in - you can't even tell what it's a pic of. May be related to this edit

![image](https://cloud.githubusercontent.com/assets/1858187/5371993/e6d842a6-800f-11e4-9045-499230148fef.png)

**Comment by zzimbler** [comment]
I think we fixed this right?

**Comment by amyleesterling** [comment]
i don't know :/

On Mon, Feb 9, 2015 at 12:57 PM, Zachary Zimbler notifications@github.com
wrote:

> I think we fixed this right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEDxMusic/Wordpress-Theme/issues/10#issuecomment-73556382
> .

## 

Director, EyeWire http://eyewire.org/ | Founder, TEDx Music Project
http://tedxmusicproject.com/
@amyleerobinson https://twitter.com/amyleerobinson

**Comment by amyleesterling** [comment]
yea it seems okay
