### ISSUE TITLE
Feature image MIA when sharing http://tedxmusicproject.com/ on social sites

### ISSUE THREAD

**Issue by amyleesterling** [TEDxMusic/Wordpress-Theme#12]
![image](https://cloud.githubusercontent.com/assets/1858187/5195734/a89e2076-74ef-11e4-8d0e-c09447a1ccdf.png)

**Comment by jwenerd** [comment]
I see you are using Jetpack for this... It adds will blank image as the social image meta tag as default if it can't detect anything automatically within a post or page. 

@zzimbler  we can use the "jetpack_open_graph_image_default" to return a default image to return to the og:image meta tag if nothing is found. 

demo - example to add to theme:

```

add_filter('jetpack_open_graph_image_default','tedx_music_og_image_default');

function tedx_music_og_image_default($img) {

  $img =  '//:tedxmusicproject.com/wp-content/uploads/og-default.png';
  // or whatever path in theme using get_template_directory_uri() 
  return $img
}

```

**Comment by mgrema** [comment]
I think this is a quick fix of just adding a blavatar or a featured image on the first page:
http://en.support.wordpress.com/facebook-image-thumbnail/
I added a featured image, but it may need to update the media content. Check later if it appears on a post.

**Comment by jwenerd** [comment]
You are correct @mgrema  adding the feature imagine to the home page did set the tag:
![screen shot 2014-11-26 at 12 59 15 am](https://cloud.githubusercontent.com/assets/1452285/5196883/8d6ae8f8-7507-11e4-86cb-96383988a1db.png)

**Comment by zzimbler** [comment]
so is this fixed, can we close this out? @jwenerd @mgrema

**Comment by jwenerd** [comment]
Yep @zzimbler  - adding the logo to the page as the featured image created that meta tag.
