### ISSUE TITLE
SoundCloud MIA feature image

### ISSUE THREAD

**Issue by amyleesterling** [TEDxMusic/Wordpress-Theme#14]
I know this isn't wordpress but I wanted to log this somewhere without creating a new repo. Wrote into SoundCloud support about our MIA feature image. Alos Tweeted @SoundCloudDevs about collaboration.

Hey SoundCloud!
First, you all are awesome. Second, a quick question. We recently noticed that when people share our music or profile page on social networks there is no thumbnail image, despite the fact that we have both a profile image and feature images for each of our 400 tracks. Could you help us figure out why this is happening?
Thanks!
Amy and the TEDx Music Project team

![image](https://cloud.githubusercontent.com/assets/1858187/5237141/be87d472-783c-11e4-86ce-29bacc37f81e.png)

**Comment by zzimbler** [comment]
http://help.soundcloud.com/customer/portal/articles/243072-what-image-is-used-when-i-share-to-facebook-

**Comment by amyleesterling** [comment]
I contacted SoundCloud and Buffer on this - it seems to be a problem with
the link sharing service we use with Buffer (the tool that schedules all
our posts). Bit.ly and buff.ly links don't pull soundcloud's feature images
for whatever reason. So far the only solution I can find is to go back in
and manually update the links to not be shortened.. there are some 60 of
them scheduled through April. Must find time to do it.

On Tuesday, December 9, 2014, Zachary Zimbler notifications@github.com
wrote:

> http://help.soundcloud.com/customer/portal/articles/243072-what-image-is-used-when-i-share-to-facebook-
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEDxMusic/Wordpress-Theme/issues/14#issuecomment-66293147
> .

## 

Sent by Droid

**Comment by amyleesterling** [comment]
![image](https://cloud.githubusercontent.com/assets/1858187/5371960/5808d946-800f-11e4-9c02-b4e3652202a9.png)
