### ISSUE TITLE
urls pointing to same place

### ISSUE THREAD

**Issue by zzimbler** [TEDxMusic/Wordpress-Theme#5]
TEDxGlobalMusicProject.com should forward to the TEDxMusicProject.com site.

**Comment by zzimbler** [comment]
I updated GoDaddy so all of the tedxmusic related domains that you own should redirect to http://tedxmusicproject.com. I'm not sure how long it'll take to propagate those changes so we should check back in like ~24hrs to make sure it actually works before closing out this task.

**Comment by amyleesterling** [comment]
Thanks Zach!

Redirect is working now!

On Tue, Jul 8, 2014 at 12:06 AM, Zachary Zimbler notifications@github.com
wrote:

> I updated GoDaddy so all of the tedxmusic related domains that you own
> should redirect to http://tedxmusicproject.com. I'm not sure how long
> it'll take to propagate those changes so we should check back in like
> ~24hrs to make sure it actually works before closing out this task.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEDxMusic/Wordpress-Theme/issues/5#issuecomment-48270059
> .

## 

Creative Director, EyeWire http://eyewire.org/ // Founder, TEDx
Music Project https://soundcloud.com/tedxmusicproject
blog http://www.amyrobinson.wordpress.com/ // t
http://www.twitter.com/amyleerobinson // g+
https://plus.google.com/u/0/111790801286012681940/posts
